[package]
name = "swissarmyhammer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
colored = "2"
is-terminal = "0.4"
rmcp = { version = "0.1.5", features = ["server", "transport-io"] }
