[package]
name = "swissarmyhammer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
colored = "2"
is-terminal = "0.4"
rmcp = { version = "0.1.5", features = ["server", "transport-io"] }
walkdir = "2"
dirs = "5"
rust-embed = "8"
notify = "6"
dashmap = "6"
regex = "1"
tabled = "0.15"
liquid = "0.26"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.0"
proptest = "1.0"
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
# Enable Link Time Optimization for smaller binaries
lto = true
# Strip debug symbols
strip = true
# Enable all optimizations
opt-level = 3
# Reduce code generation units for better optimization
codegen-units = 1
# Abort on panic for smaller binary size
panic = "abort"
