name: Bug Report
description: File a bug report to help us improve SwissArmyHammer
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us diagnose and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SwissArmyHammer Version
      description: What version of SwissArmyHammer are you running? (Run `swissarmyhammer --version`)
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Code Version
      description: What version of Claude Code are you using? (if applicable)
      placeholder: "3.0.0"
    validations:
      required: false

  - type: textarea
    id: doctor-output
    attributes:
      label: Doctor Command Output
      description: Please run `swissarmyhammer doctor` and paste the output here
      placeholder: Paste the output of `swissarmyhammer doctor` here
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your MCP configuration (remove any sensitive information)
      placeholder: |
        {
          "mcpServers": {
            "swissarmyhammer": {
              "command": "swissarmyhammer",
              "args": ["serve"]
            }
          }
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Screenshots can be very helpful!
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have run `swissarmyhammer doctor` to check for common issues
          required: true
        - label: I am using the latest version of SwissArmyHammer
          required: false