name: Feature Request
description: Suggest an idea for SwissArmyHammer
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: What type of feature is this?
      description: What category does this feature fall into?
      options:
        - Core functionality
        - CLI improvement
        - Documentation
        - Performance
        - Developer experience
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: Help us prioritize by indicating how important this feature is
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical for adoption
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        1. When working with...
        2. During development of...
        3. For teams that...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas about how this could be implemented, please share them
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: false