name: Question / Help
description: Ask a question or get help with SwissArmyHammer
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Before submitting, please check:
        - 📖 [Documentation](https://wballard.github.io/swissarmyhammer)
        - 🔍 [Existing issues](https://github.com/wballard/swissarmyhammer/issues)
        - 💬 [GitHub Discussions](https://github.com/wballard/swissarmyhammer/discussions) (for general questions)

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please describe what you're trying to accomplish or what you need help with.
      placeholder: I'm trying to... but I'm having trouble with...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question category
      description: What area does your question relate to?
      options:
        - Installation
        - Configuration
        - Creating prompts
        - Claude Code integration
        - MCP protocol
        - CLI usage
        - Troubleshooting
        - Best practices
        - Other
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What have you tried?
      description: Please describe what you've already attempted.
      placeholder: |
        1. I tried...
        2. I looked at...
        3. I read...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: SwissArmyHammer Version
      description: What version are you using? (Run `swissarmyhammer --version`)
      placeholder: "0.1.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: false

  - type: textarea
    id: doctor-output
    attributes:
      label: Doctor Command Output (if relevant)
      description: If your question is about setup or configuration, please run `swissarmyhammer doctor` and paste the output
      placeholder: Paste the output of `swissarmyhammer doctor` here
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Please share your MCP configuration if it's relevant to your question (remove sensitive information)
      placeholder: |
        {
          "mcpServers": {
            "swissarmyhammer": {
              "command": "swissarmyhammer",
              "args": ["serve"]
            }
          }
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about your question here. Examples, screenshots, and error messages are very helpful!
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues
          required: true
        - label: This is a specific question about using SwissArmyHammer
          required: true