[build]
# Enable parallel compilation with all available cores
# Note: Install sccache with `cargo install sccache` for faster rebuilds
# rustc-wrapper = "sccache"

[target.aarch64-apple-darwin]
# Use system linker on Apple Silicon
rustflags = ["-C", "link-arg=-Wl,-ld_classic"]

[target.x86_64-apple-darwin]
# Use system linker on Intel macOS
rustflags = ["-C", "link-arg=-Wl,-ld_classic"]

[registries.crates-io]
protocol = "sparse"

# Cache settings for faster subsequent builds
[net]
git-fetch-with-cli = true

# Faster cargo commands
[cargo-new]
vcs = "none"