# SwissArmyHammer Basic Configuration Example (TOML)
# This file demonstrates common configuration patterns in TOML format

# Application information
[app]
name = "SwissArmyHammer"
version = "2.0.0"
description = "Program all the things, just by writing markdown"
author = "Your Name"
debug = false
environment = "development"

# Database configuration
[database]
host = "localhost"
port = 5432
database = "swissarmyhammer"
ssl_enabled = false
timeout_seconds = 30
max_connections = 10

# Database credentials (use environment variables in production)
[database.credentials]
username = "admin" 
password = "${DATABASE_PASSWORD:-defaultpass}"

# Feature flags
[features]
telemetry = true
experimental = false
advanced_logging = false
auto_updates = true
beta_features = false

# Template variables for liquid templates
[variables]
project_root = "/path/to/project"
build_date = "2024-01-15"
contact_email = "admin@example.com"
organization = "Your Organization"
license = "MIT"

# Logging configuration
[logging]
level = "info"
format = "json"
output = "stdout"
rotation = "daily"

# API configuration
[api]
base_url = "https://api.example.com"
version = "v1"
timeout_seconds = 60
retry_attempts = 3

# Cache settings
[cache]
enabled = true
ttl_seconds = 3600
max_size_mb = 100
provider = "memory"

# Development tools
[tools]
editor = "code"
browser = "chrome"
terminal = "zsh"