# SwissArmyHammer Web Application Configuration Example (TOML)
# This configuration demonstrates settings for web application development

# Application configuration
[app]
name = "MyWebApp"
version = "1.0.0"
description = "A modern web application built with SwissArmyHammer"
author = "Web Development Team"
debug = true
environment = "development"
base_url = "http://localhost:3000"

# Web server configuration
[server]
host = "0.0.0.0"
port = 3000
ssl_enabled = false
cors_enabled = true
session_timeout = 3600
max_request_size = "10MB"

# Database configuration for web app
[database]
host = "${DB_HOST:-localhost}"
port = 5432
database = "webapp_db"
ssl_enabled = false
pool_size = 10
connection_timeout = 30

[database.credentials]
username = "${DB_USER:-webapp_user}"
password = "${DB_PASSWORD:-webapp_password}"

# Authentication & authorization
[auth]
jwt_secret = "${JWT_SECRET:-dev-secret-change-in-production}"
jwt_expiry_hours = 24
password_min_length = 8
session_store = "database"
oauth_enabled = true

# OAuth providers
[auth.providers.google]
client_id = "${GOOGLE_CLIENT_ID}"
client_secret = "${GOOGLE_CLIENT_SECRET}"
redirect_url = "/auth/google/callback"

[auth.providers.github]
client_id = "${GITHUB_CLIENT_ID}"
client_secret = "${GITHUB_CLIENT_SECRET}" 
redirect_url = "/auth/github/callback"

# Frontend build configuration
[frontend]
framework = "react"
build_tool = "vite"
dev_server_port = 5173
hot_reload = true
source_maps = true
minify = false

# Asset management
[assets]
public_dir = "public"
upload_dir = "uploads"
max_file_size = "5MB"
allowed_types = ["jpg", "png", "gif", "pdf", "docx"]
cdn_enabled = false
cdn_url = "${CDN_URL}"

# Email configuration
[email]
provider = "smtp"
smtp_host = "${SMTP_HOST:-localhost}"
smtp_port = 587
smtp_user = "${SMTP_USER}"
smtp_password = "${SMTP_PASSWORD}"
from_address = "noreply@example.com"
from_name = "MyWebApp"

# Redis cache configuration
[cache]
provider = "redis"
redis_url = "${REDIS_URL:-redis://localhost:6379}"
default_ttl = 3600
session_ttl = 86400

# API rate limiting
[rate_limit]
enabled = true
requests_per_minute = 100
burst_size = 20
whitelist = ["127.0.0.1", "::1"]

# Monitoring and analytics
[monitoring]
enabled = true
error_tracking = "sentry"
sentry_dsn = "${SENTRY_DSN}"
metrics_enabled = true
performance_monitoring = true

# Template variables for web app templates
[variables]
app_title = "My Web Application"
meta_description = "A powerful web application built with modern tools"
meta_keywords = "web, app, react, development"
copyright_year = "2024"
support_email = "support@example.com"
privacy_policy_url = "/privacy"
terms_of_service_url = "/terms"

# Development tools
[development]
hot_reload = true
debug_toolbar = true
profiler = true
sql_logging = true
template_debugging = true

# Feature flags for web app
[features]
user_registration = true
email_verification = true
password_reset = true
admin_dashboard = true
api_documentation = true
rate_limiting = true
file_uploads = true
real_time_notifications = false
dark_mode = true
multi_language = false