name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust with Cache
        uses: ./.github/actions/setup-rust-cache

      - name: Publish swissarmyhammer library
        run: cargo publish --package swissarmyhammer --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for library to be available
        run: sleep 30

      - name: Publish swissarmyhammer-cli
        run: cargo publish --package swissarmyhammer-cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
